import React from "react";

export function VerticalVerificationTimeline({ steps }) {
  const defaultSteps = [
    { title: "QR Session Initialized", time: "10:00 AM", status: "completed", desc: "Cryptographic session token generated by faculty terminal" },
    { title: "Camera QR Frame Scan", time: "10:02 AM", status: "completed", desc: "Student camera captured dynamic 5-minute session payload" },
    { title: "Course Enrollment Check", time: "10:02 AM", status: "completed", desc: "Verified active enrollment in CS501 Database Systems" },
    { title: "Attendance Log Committed", time: "10:02 AM", status: "completed", desc: "Status 'PRESENT' committed to immutable backend ledger" },
  ];

  const timelineSteps = steps || defaultSteps;

  return (
    <div className="space-y-4">
      <h4 className="font-serif text-base font-bold text-[#12181F]">Verification Audit Log</h4>
      <div className="relative pl-6 border-l-2 border-[#D8D2C4] space-y-6">
        {timelineSteps.map((step, idx) => (
          <div key={idx} className="relative">
            <div className="absolute -left-[31px] top-0 w-4 h-4 rounded-full bg-[#2E6B34] border-2 border-white flex items-center justify-center">
              <span className="w-1.5 h-1.5 rounded-full bg-white"></span>
            </div>
            <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-1">
              <h5 className="font-bold text-xs text-[#12181F]">{step.title}</h5>
              <span className="font-mono text-[10px] text-[#6B7280] font-semibold">{step.time}</span>
            </div>
            <p className="text-xs text-[#555E68] mt-0.5">{step.desc}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
