import React from "react";

export function VerticalVerificationTimeline({ steps }) {
  const defaultSteps = [
    { title: "QR Session Initialized", time: "10:00 AM", status: "completed", desc: "Cryptographic session token generated by faculty terminal" },
    { title: "Camera QR Frame Scan", time: "10:02 AM", status: "completed", desc: "Student camera captured dynamic 5-minute session payload" },
    { title: "Anti-Proxy GPS Geo-Fence", time: "10:02 AM", status: "completed", desc: "Physical classroom radius locked & verified (inside perimeter)" },
    { title: "Attendance Log Committed", time: "10:02 AM", status: "completed", desc: "Status 'PRESENT' committed to immutable backend ledger" },
  ];

  const timelineSteps = steps || defaultSteps;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between pb-2 border-b border-slate-100">
        <h4 className="text-sm font-bold text-slate-900 flex items-center gap-2">
          <span className="material-symbols-outlined text-blue-600 text-base">verified_user</span>
          <span>Security & Verification Audit</span>
        </h4>
        <span className="text-[10px] uppercase font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
          Enforced
        </span>
      </div>
      <div className="relative pl-6 border-l-2 border-slate-200 space-y-5">
        {timelineSteps.map((step, idx) => (
          <div key={idx} className="relative">
            <div className="absolute -left-[31px] top-0.5 w-3.5 h-3.5 rounded-full bg-emerald-600 border-2 border-white flex items-center justify-center shadow-xs">
              <span className="w-1 h-1 rounded-full bg-white"></span>
            </div>
            <div className="flex flex-col sm:flex-row justify-between sm:items-baseline gap-1">
              <h5 className="font-bold text-xs text-slate-900 tracking-tight">{step.title}</h5>
              <span className="font-mono text-[10px] text-slate-400 font-semibold">{step.time}</span>
            </div>
            <p className="text-xs text-slate-500 mt-0.5 leading-relaxed">{step.desc}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

