-- LectureLog Supabase/PostgreSQL migration
-- Run this in Supabase Dashboard -> SQL Editor.

DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM ('HOD', 'FACULTY', 'STUDENT');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE public.attendance_status AS ENUM ('PRESENT', 'ABSENT', 'LATE');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar(120) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  role public.user_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.faculty (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.subjects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_code varchar(30) NOT NULL UNIQUE,
  subject_name varchar(150) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lectures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id bigint NOT NULL REFERENCES public.subjects(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  faculty_id bigint NOT NULL REFERENCES public.faculty(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  lecture_date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lectures_time_order CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_lectures_faculty_date ON public.lectures (faculty_id, lecture_date, start_time);
CREATE INDEX IF NOT EXISTS idx_lectures_subject ON public.lectures (subject_id);

CREATE TABLE IF NOT EXISTS public.qr_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lecture_id bigint NOT NULL REFERENCES public.lectures(id) ON UPDATE CASCADE ON DELETE CASCADE,
  session_token char(64) NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_qr_sessions_lecture_expiry ON public.qr_sessions (lecture_id, expires_at);

CREATE TABLE IF NOT EXISTS public.attendance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lecture_id bigint NOT NULL REFERENCES public.lectures(id) ON UPDATE CASCADE ON DELETE CASCADE,
  student_id bigint NOT NULL REFERENCES public.students(id) ON UPDATE CASCADE ON DELETE CASCADE,
  status public.attendance_status NOT NULL DEFAULT 'PRESENT',
  attendance_time timestamptz NOT NULL DEFAULT now(),
  UNIQUE (lecture_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_student_time ON public.attendance (student_id, attendance_time DESC);

INSERT INTO public.subjects (subject_code, subject_name)
VALUES ('DEMO-101', 'Demo Subject')
ON CONFLICT (subject_code) DO UPDATE SET subject_name = EXCLUDED.subject_name;

-- After creating users through POST /register, link their profiles:
-- INSERT INTO public.students (user_id) VALUES (<student_user_id>);
-- INSERT INTO public.faculty (user_id) VALUES (<faculty_user_id>);

-- This project uses its own users table and JWT login. Supabase Auth is not required
-- for the current backend. Enable RLS and add policies only if the frontend queries
-- Supabase directly in a later version.
